### ISSUE TITLE
json file error

### ISSUE THREAD

**Issue by pierrotm777** [NicoHood/HoodLoader2#10] opened 2015-06-01 08:55 UTC
your link https://github.com/NicoHood/HoodLoader2/releases/download/2.0.4/2.0.4-boards_manager.zip
return an error

**Comment by NicoHood** [comment] 2015-06-01 17:38
now online, missed the upload.
If it works, please close the issue. Thanks for the report!

**Comment by pierrotm777** [comment] 2015-06-01 18:02
Return me again an error

	... 1 more
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.FileInputStream@5ccbe0; line: 4, column: 2]

**Comment by per1234** [comment] 2015-06-01 19:38
I just installed it under 1.6.4 and the hourly build with no problem. Maybe the problem is caused by the first failed install attempt before NicoHood had uploaded the archive. @pierrotm777 try deleting:

arduino15/package_NicoHood_HoodLoader2_index.json
arduino15/package_NicoHood_HoodLoader2_index.json.sig.tmp
arduino15/packages/HoodLoader2/
arduino15/staging/packages/2.0.4-boards_manager.zip

and then try installing again and let us know if you still have the problem.

**Comment by NicoHood** [comment] 2015-06-15 17:53
Issue solved?

**Comment by pierrotm777** [comment] 2015-06-15 17:56
Yes , thanks :-)

2015-06-15 19:53 GMT+02:00 Nico <notifications@github.com>:

**Closed** 2015-06-15 18:05 UTC
